*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMV_LOGALI......................................*
FORM GET_DATA_ZMV_LOGALI.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZEMPLOY_LOGALI WHERE
(VIM_WHERETAB) .
    CLEAR ZMV_LOGALI .
ZMV_LOGALI-CLIENT =
ZEMPLOY_LOGALI-CLIENT .
ZMV_LOGALI-ADDRESS_NUMBER =
ZEMPLOY_LOGALI-ADDRESS_NUMBER .
ZMV_LOGALI-NAME =
ZEMPLOY_LOGALI-NAME .
ZMV_LOGALI-LASTN1 =
ZEMPLOY_LOGALI-LASTN1 .
ZMV_LOGALI-LASTN2 =
ZEMPLOY_LOGALI-LASTN2 .
ZMV_LOGALI-PROF_CAT =
ZEMPLOY_LOGALI-PROF_CAT .
ZMV_LOGALI-STATUS =
ZEMPLOY_LOGALI-STATUS .
ZMV_LOGALI-COUNTRY_G1 =
ZEMPLOY_LOGALI-COUNTRY_G1 .
<VIM_TOTAL_STRUC> = ZMV_LOGALI.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMV_LOGALI .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMV_LOGALI.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMV_LOGALI-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZEMPLOY_LOGALI WHERE
  ADDRESS_NUMBER = ZMV_LOGALI-ADDRESS_NUMBER .
    IF SY-SUBRC = 0.
    DELETE ZEMPLOY_LOGALI .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZEMPLOY_LOGALI WHERE
  ADDRESS_NUMBER = ZMV_LOGALI-ADDRESS_NUMBER .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZEMPLOY_LOGALI.
    ENDIF.
ZEMPLOY_LOGALI-CLIENT =
ZMV_LOGALI-CLIENT .
ZEMPLOY_LOGALI-ADDRESS_NUMBER =
ZMV_LOGALI-ADDRESS_NUMBER .
ZEMPLOY_LOGALI-NAME =
ZMV_LOGALI-NAME .
ZEMPLOY_LOGALI-LASTN1 =
ZMV_LOGALI-LASTN1 .
ZEMPLOY_LOGALI-LASTN2 =
ZMV_LOGALI-LASTN2 .
ZEMPLOY_LOGALI-PROF_CAT =
ZMV_LOGALI-PROF_CAT .
ZEMPLOY_LOGALI-STATUS =
ZMV_LOGALI-STATUS .
ZEMPLOY_LOGALI-COUNTRY_G1 =
ZMV_LOGALI-COUNTRY_G1 .
    IF SY-SUBRC = 0.
    UPDATE ZEMPLOY_LOGALI ##WARN_OK.
    ELSE.
    INSERT ZEMPLOY_LOGALI .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMV_LOGALI-UPD_FLAG,
STATUS_ZMV_LOGALI-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZMV_LOGALI.
  SELECT SINGLE * FROM ZEMPLOY_LOGALI WHERE
ADDRESS_NUMBER = ZMV_LOGALI-ADDRESS_NUMBER .
ZMV_LOGALI-CLIENT =
ZEMPLOY_LOGALI-CLIENT .
ZMV_LOGALI-ADDRESS_NUMBER =
ZEMPLOY_LOGALI-ADDRESS_NUMBER .
ZMV_LOGALI-NAME =
ZEMPLOY_LOGALI-NAME .
ZMV_LOGALI-LASTN1 =
ZEMPLOY_LOGALI-LASTN1 .
ZMV_LOGALI-LASTN2 =
ZEMPLOY_LOGALI-LASTN2 .
ZMV_LOGALI-PROF_CAT =
ZEMPLOY_LOGALI-PROF_CAT .
ZMV_LOGALI-STATUS =
ZEMPLOY_LOGALI-STATUS .
ZMV_LOGALI-COUNTRY_G1 =
ZEMPLOY_LOGALI-COUNTRY_G1 .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMV_LOGALI USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMV_LOGALI-ADDRESS_NUMBER TO
ZEMPLOY_LOGALI-ADDRESS_NUMBER .
MOVE ZMV_LOGALI-CLIENT TO
ZEMPLOY_LOGALI-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZEMPLOY_LOGALI'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZEMPLOY_LOGALI TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZEMPLOY_LOGALI'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
