*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMV_MARD_LOGALI.................................*
FORM GET_DATA_ZMV_MARD_LOGALI.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM MARD WHERE
(VIM_WHERETAB) .
    CLEAR ZMV_MARD_LOGALI .
ZMV_MARD_LOGALI-MANDT =
MARD-MANDT .
ZMV_MARD_LOGALI-MATNR =
MARD-MATNR .
ZMV_MARD_LOGALI-WERKS =
MARD-WERKS .
ZMV_MARD_LOGALI-LGORT =
MARD-LGORT .
ZMV_MARD_LOGALI-PSTAT =
MARD-PSTAT .
ZMV_MARD_LOGALI-LFGJA =
MARD-LFGJA .
ZMV_MARD_LOGALI-LFMON =
MARD-LFMON .
ZMV_MARD_LOGALI-UMLME =
MARD-UMLME .
ZMV_MARD_LOGALI-INSME =
MARD-INSME .
<VIM_TOTAL_STRUC> = ZMV_MARD_LOGALI.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMV_MARD_LOGALI .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMV_MARD_LOGALI.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMV_MARD_LOGALI-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM MARD WHERE
  MATNR = ZMV_MARD_LOGALI-MATNR AND
  WERKS = ZMV_MARD_LOGALI-WERKS AND
  LGORT = ZMV_MARD_LOGALI-LGORT .
    IF SY-SUBRC = 0.
    DELETE MARD .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM MARD WHERE
  MATNR = ZMV_MARD_LOGALI-MATNR AND
  WERKS = ZMV_MARD_LOGALI-WERKS AND
  LGORT = ZMV_MARD_LOGALI-LGORT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR MARD.
    ENDIF.
MARD-MANDT =
ZMV_MARD_LOGALI-MANDT .
MARD-MATNR =
ZMV_MARD_LOGALI-MATNR .
MARD-WERKS =
ZMV_MARD_LOGALI-WERKS .
MARD-LGORT =
ZMV_MARD_LOGALI-LGORT .
MARD-PSTAT =
ZMV_MARD_LOGALI-PSTAT .
MARD-LFGJA =
ZMV_MARD_LOGALI-LFGJA .
MARD-LFMON =
ZMV_MARD_LOGALI-LFMON .
MARD-UMLME =
ZMV_MARD_LOGALI-UMLME .
MARD-INSME =
ZMV_MARD_LOGALI-INSME .
    IF SY-SUBRC = 0.
    UPDATE MARD ##WARN_OK.
    ELSE.
    INSERT MARD .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMV_MARD_LOGALI-UPD_FLAG,
STATUS_ZMV_MARD_LOGALI-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMV_MARD_LOGALI.
  SELECT SINGLE * FROM MARD WHERE
MATNR = ZMV_MARD_LOGALI-MATNR AND
WERKS = ZMV_MARD_LOGALI-WERKS AND
LGORT = ZMV_MARD_LOGALI-LGORT .
ZMV_MARD_LOGALI-MANDT =
MARD-MANDT .
ZMV_MARD_LOGALI-MATNR =
MARD-MATNR .
ZMV_MARD_LOGALI-WERKS =
MARD-WERKS .
ZMV_MARD_LOGALI-LGORT =
MARD-LGORT .
ZMV_MARD_LOGALI-PSTAT =
MARD-PSTAT .
ZMV_MARD_LOGALI-LFGJA =
MARD-LFGJA .
ZMV_MARD_LOGALI-LFMON =
MARD-LFMON .
ZMV_MARD_LOGALI-UMLME =
MARD-UMLME .
ZMV_MARD_LOGALI-INSME =
MARD-INSME .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMV_MARD_LOGALI USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMV_MARD_LOGALI-MATNR TO
MARD-MATNR .
MOVE ZMV_MARD_LOGALI-WERKS TO
MARD-WERKS .
MOVE ZMV_MARD_LOGALI-LGORT TO
MARD-LGORT .
MOVE ZMV_MARD_LOGALI-MANDT TO
MARD-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'MARD'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN MARD TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'MARD'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
